services:
  scanperson.ui:
    environment:
        - IDENTITY_API_DOMEN=${IDENTITY_API_DOMEN}
        - SCANPERSON_WEBAPI_DOMEN=${SCANPERSON_WEBAPI_DOMEN}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - CHOKIDAR_USEPOLLING=true
      
  scanperson.webapi:
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
        - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - JWT_OPTIONS_SECRET_KEY=${JWT_OPTIONS_SECRET_KEY}
        - HTMLWEBRU_API_KEY=${HTMLWEBRU_API_KEY}
        - AUTO_MAPPER_LICENSE_KEY=${AUTO_MAPPER_LICENSE_KEY}
        - ConnectionStrings__ScanPersonDb=${ConnectionStrings__ScanPersonDb}
        - HOST_HTTPS_PATH=${HOST_HTTPS_PATH}
        - IS_CACHE_ENABLE=${IS_CACHE_ENABLE}
        - CACHE_EXPIRATION=${CACHE_EXPIRATION}

  scanpersondb:
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        PGDATA: ${PGDATA}

      
