@ScanPerson.WebApi_HostAddress = https://localhost:8081

GET {{ScanPerson.WebApi_HostAddress}}/api/WeatherForecast
Accept: application/json

###

GET {{ScanPerson.WebApi_HostAddress}}/api/Test
Accept: application/json

###

