services:
  telegrambots:
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - SCAN_PERSON_BOT_TOKEN=${SCAN_PERSON_BOT_TOKEN}
        - AUTO_MAPPER_LICENSE_KEY=${AUTO_MAPPER_LICENSE_KEY}