services:
  identity.api:
    container_name: identityapi
    image: identityapi
    restart: always
    build:
      context: .
      dockerfile: ./Identity.Api/Dockerfile
    depends_on:
      identitydb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - JWT_OPTIONS_SECRET_KEY=${JWT_OPTIONS_SECRET_KEY}
      - ConnectionStrings__IdentityDb=${ConnectionStrings__IdentityDb}
      - APP_UID=${APP_UID}
      - HOST_MAIN_PATH=${HOST_MAIN_PATH}
    ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - ${HOST_MAIN_PATH}/Identity/Identity.Api/${ASPNETCORE_Kestrel__Certificates__Default__Path}:${ASPNETCORE_Kestrel__Certificates__Default__Path}
    networks:
      - scanperson-network

  identitydb:
    container_name: identitydb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - 5434:5432
    volumes:
      - identitydb:/data/identitydb
    networks:
      - scanperson-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  identitypgadmin:
    container_name: identitypgadmin
    image: dpage/pgadmin4
    restart: always
    depends_on:
      identitydb:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - identitydb:/data/identitydb
      - identitypgadmin:/var/lib/identitypgadmin
    ports:
      - 8001:80
    networks:
      - scanperson-network

networks:
  scanperson-network:
    external: true
    driver: bridge

volumes:
  identitydb:
  identitypgadmin: