services:
  identity.api:
    environment:
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
        - ASPNETCORE_HTTP_PORTS=8090
        - ASPNETCORE_HTTPS_PORTS=8091
        - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
        - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - JWT_OPTIONS_SECRET_KEY=${JWT_OPTIONS_SECRET_KEY}
        - ConnectionStrings__IdentityDb=${ConnectionStrings__IdentityDb}
        - HOST_HTTPS_PATH=${HOST_HTTPS_PATH}

  identitydb:
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${IDENTITY_POSTGRES_DB}
        PGDATA: ${PGDATA}
      
