services:
  identity.api:
    container_name: identityapi
    image: identityapi
    restart: always
    build:
      context: .
      dockerfile: ./Identity.Api/Dockerfile
    depends_on:
      identitydb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${ASPNETCORE_Kestrel__Certificates__Default__Path}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - JWT_OPTIONS_SECRET_KEY=${JWT_OPTIONS_SECRET_KEY}
      - ConnectionStrings__IdentityDb=${ConnectionStrings__IdentityDb}
      - HOST_HTTPS_PATH=${HOST_HTTPS_PATH}
    ports:
      - 8090:8090
      - 8091:8091
    volumes:
      - ${HOST_HTTPS_PATH}:${ASPNETCORE_Kestrel__Certificates__Default__Path}
    networks:
      - scanperson-network

  identitydb:
    container_name: identitydb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${IDENTITY_POSTGRES_DB}
      PGDATA: ${PGDATA}
    ports:
      - 5434:5432
    volumes:
      - identitydbdata:/data/identitydb
    networks:
      - scanperson-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  scanperson-network:
    external: true
    driver: bridge
volumes:
  identitydbdata:
