//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScanPerson.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScanPerson.Common.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while performing the operation..
        /// </summary>
        public static string ClientOperationError {
            get {
                return ResourceManager.GetString("ClientOperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable {0} not found..
        /// </summary>
        public static string EnvironmentNotFound {
            get {
                return ResourceManager.GetString("EnvironmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing data..
        /// </summary>
        public static string InitDataError {
            get {
                return ResourceManager.GetString("InitDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login or password has error..
        /// </summary>
        public static string LoginOrPasswordHasError {
            get {
                return ResourceManager.GetString("LoginOrPasswordHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while performing the operation of {0}..
        /// </summary>
        public static string OperationError {
            get {
                return ResourceManager.GetString("OperationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input of the operation contains the object: {0}..
        /// </summary>
        public static string OperationInput {
            get {
                return ResourceManager.GetString("OperationInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of the operation contains the object: {0}..
        /// </summary>
        public static string OperationResult {
            get {
                return ResourceManager.GetString("OperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section {0} not found or have error..
        /// </summary>
        public static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method called {0} started..
        /// </summary>
        public static string StartedMethod {
            get {
                return ResourceManager.GetString("StartedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method called {0} started with parameters {1}..
        /// </summary>
        public static string StartedMethodWithParameters {
            get {
                return ResourceManager.GetString("StartedMethodWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such user is exist..
        /// </summary>
        public static string UserAlredyExist {
            get {
                return ResourceManager.GetString("UserAlredyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
