# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev", "#5_add_ci_cd_pipeline" ]
  pull_request:
    branches: [ "dev", "#5_add_ci_cd_pipeline" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Change directory to solution folder
      run: cd ./ScanPerson
    - name: Clean build artifacts
      run: |
        find . -type d -name "bin" -exec rm -rf {} +
        find . -type d -name "obj" -exec rm -rf {} +
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
    - name: Clean solution
      run: dotnet clean ./ScanPerson/ScanPerson.sln
    - name: Restore dependencies
      run: dotnet restore ./ScanPerson/ScanPerson.sln
    - name: Build
      run: dotnet build --no-restore ./ScanPerson/ScanPerson.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./ScanPerson/ScanPerson.sln
