# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Push to VM, Build and UP Docker Compose

on:
  pull_request:
    branches: [ "dev", "prod" ]
  push:
    branches: [ "dev", "prod" ]
  workflow_call:
  # can be triggered manually
  workflow_dispatch:
jobs:
  continuous-delivery:
  # add conditional only merged pull requests to prod
    # if: |
    #   ${{ (github.event.workflow_run.conclusion == 'success' &&
    #     github.event.workflow_run.head_branch == 'dev') ||
    #     github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print a github.event.workflow_run.conclusion 
        run: echo github.event.workflow_run.conclusion - ${{ github.event.workflow_run.conclusion }}
      - name: Print a github.event.workflow_run.head_branch 
        run: echo github.event.workflow_run.head_branch - ${{ github.event.workflow_run.head_branch }}
      - name: Print a github.event_name 
        run: echo github.event_name - ${{ github.event_name }}
  
      - name: Checkout to the branch
        uses: actions/checkout@v4

      # Add step for clean directory in task #50

      # Prepare before Deploy to VM and build containers
      - name: Prepare before deploy to VM and build containers
        uses: appleboy/ssh-action@v1.2.2
        env:
          #Common
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          IS_REMOVE_IMAGE: true
          IS_REMOVE_VOLUMES: true
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Check and stop running containers (short alternative docker stop $(docker ps -qa) || true)"
            if [ -n "$(docker ps -qa)" ]; then
              echo "Stopping running containers..."
              docker stop $(docker ps -qa)
            else
              echo "No running containers to stop."
            fi

            echo "Check and remove stopped containers (short alternative docker rm $(docker ps -qa) || true)"
            if [ -n "$(docker ps -a -q)" ]; then
              echo "Removing stopped containers..."
              docker rm $(docker ps -a -q)
            else
              echo "No stopped containers to remove."
            fi

            echo "Check and remove dangling images (optional, but good for cleanup)"
            if [ ${{ env.IS_REMOVE_IMAGE }} && -n "$(docker images -f dangling=true -q)" ]; then
              echo "Removing dangling images..."
              docker image prune -f
            fi

            echo "Check and remove unused Docker volumes."
            if [ ${{ env.IS_REMOVE_VOLUMES }} && -n "$(docker volume ls -qf dangling=true)" ]; then
              echo "Removing dangling volumes..."
              docker volume prune -f
            else
              echo "No dangling volumes to remove."
            fi

            echo "Ensure network exists or create it"
            if ! docker network ls | grep -q 'scanperson-network'; then
            echo "Create docker network - scanperson-network."
            docker network create -d bridge scanperson-network
            else
            echo "Network 'scanperson-network' is exists."
            fi

            echo "Change permission for Repositories folder."
            if [ ! -d "/home/${{ env.VM_USER }}/Repositories/Pet" ]; then
              echo "Creating Pet directory..."
              mkdir -p /home/${{ env.VM_USER }}/Repositories/Pet
            fi
            echo "Directory structure prepared."
            sudo chown -R ${{ env.VM_USER }}:${{ env.VM_USER }} /home/${{ env.VM_USER }}/Repositories

      # Copy files to VM
      - name: Copy files to VM
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "Repositories/Pet"
          rm: true

      # Deploy to VM and build containers
      - name: Deploy to VM and build containers
        uses: appleboy/ssh-action@v1.2.2
        env:
          #Common
          VM_USER: ${{ secrets.VM_USER }}
          ASPNETCORE_ENVIRONMENT: ${{ vars.ASPNETCORE_ENVIRONMENT }}
          ASPNETCORE_Kestrel__Certificates__Default__Path: ${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH }}
          ASPNETCORE_Kestrel__Certificates__Default__Password: ${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD }}
          JWT_OPTIONS_SECRET_KEY: ${{ secrets.JWT_OPTIONS_SECRET_KEY }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
          PGADMIN_CONFIG_SERVER_MODE: ${{ vars.PGADMIN_CONFIG_SERVER_MODE }}
          APP_UID: ${{ secrets.VM_USER }}:${{ secrets.VM_USER }}
          HOST_MAIN_PATH: ${{ vars.HOST_MAIN_PATH }}

          # Graylog solution
          GRAYLOG_PASSWORD_SECRET: ${{ secrets.GRAYLOG_PASSWORD_SECRET }}
          GRAYLOG_ROOT_PASSWORD_SHA2: ${{ secrets.GRAYLOG_ROOT_PASSWORD_SHA2 }}

          # ScanPerson solution
          SCANPERSON_ALLOWED_HOSTS: ${{ vars.SCANPERSON_ALLOWED_HOSTS }}
          ConnectionStrings__ScanPersonDb: ${{ secrets.CONNECTIONSTRINGS__SCANPERSONDB }}
          SCANPERSON_POSTGRES_DB: ${{ vars.SCANPERSON_POSTGRES_DB }}
          IDENTITY_API_DOMEN: ${{ vars.IDENTITY_API_DOMEN }}
          SCANPERSON_WEBAPI_DOMEN: ${{ vars.SCANPERSON_WEBAPI_DOMEN }}
          HTMLWEBRU_API_KEY: ${{ secrets.HTMLWEBRU_API_KEY }}
          AUTO_MAPPER_LICENSE_KEY: ${{ secrets.AUTO_MAPPER_LICENSE_KEY }}
          SCANPERSON_PGDATA: ${{ vars.SCANPERSON_PGDATA }}

          # Identity solution
          IDENTITY_ALLOWED_HOSTS: ${{ vars.IDENTITY_ALLOWED_HOSTS }}
          ConnectionStrings__IdentityDb: ${{ secrets.CONNECTIONSTRINGS__IDENTITYDB }}
          IDENTITY_POSTGRES_DB: ${{ vars.IDENTITY_POSTGRES_DB }}
          IDENTITY_PGDATA: ${{ vars.IDENTITY_PGDATA }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add step for clone repository for first deploy in task #50
            # Navigate to the project directory on the VM
            cd Repositories/Pet

            echo "Generating development certificates..."
            mkdir -p /home/${{ env.VM_USER }}/https
            dotnet dev-certs https -ep /home/${{ env.VM_USER }}${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }} -p "${{ env.ASPNETCORE_Kestrel__Certificates__Default__Password }}"
            sudo chown -R ${{ env.VM_USER }}:${{ env.VM_USER }} /home/${{ env.VM_USER }}${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }}
            sudo chown -R ${{ env.VM_USER }}:${{ env.VM_USER }} /home/${{ env.VM_USER }}/Repositories
            
            # Rebuild and restart the Docker Compose services for all solutions.
            # The --build flag forces Docker Compose to rebuild the images locally.

            # Graylog
            echo "Graylog build and up."
            cd Graylog
            docker compose down --rmi all -v

            GRAYLOG_PASSWORD_SECRET="${{ env.GRAYLOG_PASSWORD_SECRET }}" \
            GRAYLOG_ROOT_PASSWORD_SHA2="${{ env.GRAYLOG_ROOT_PASSWORD_SHA2 }}" \
            docker compose up -d --build
            
            cd ..

            echo "Identity build and up."
            cd Identity
            docker compose down --rmi all -v

            ASPNETCORE_ENVIRONMENT="${{ env.ASPNETCORE_ENVIRONMENT }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Path="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Password="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Password }}" \
            JWT_OPTIONS_SECRET_KEY="${{ env.JWT_OPTIONS_SECRET_KEY }}" \
            POSTGRES_USER="${{ env.POSTGRES_USER }}" \
            POSTGRES_PASSWORD="${{ env.POSTGRES_PASSWORD }}" \
            PGADMIN_DEFAULT_EMAIL="${{ env.PGADMIN_DEFAULT_EMAIL }}" \
            PGADMIN_DEFAULT_PASSWORD="${{ env.PGADMIN_DEFAULT_PASSWORD }}" \
            PGADMIN_CONFIG_SERVER_MODE="${{ env.PGADMIN_CONFIG_SERVER_MODE }}" \
            ALLOWED_HOSTS="${{ env.IDENTITY_ALLOWED_HOSTS }}" \
            ConnectionStrings__IdentityDb="${{ env.ConnectionStrings__IdentityDb }}" \
            POSTGRES_DB="${{ env.IDENTITY_POSTGRES_DB }}" \
            PGDATA="${{ env.IDENTITY_PGDATA }}" \
            APP_UID="${{ env.APP_UID }}" \
            HOST_HTTPS_PATH="${{ env.HOST_HTTPS_PATH }}" \
            docker compose up -d --build

            cd ..

            echo "ScanPerson build and up."
            cd ScanPerson
            docker compose down --rmi all -v

            IDENTITY_API_DOMEN="${{ env.IDENTITY_API_DOMEN }}" \
            SCANPERSON_WEBAPI_DOMEN="${{ env.SCANPERSON_WEBAPI_DOMEN }}" \
            ASPNETCORE_ENVIRONMENT="${{ env.ASPNETCORE_ENVIRONMENT }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Path="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Password="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Password }}" \
            JWT_OPTIONS_SECRET_KEY="${{ env.JWT_OPTIONS_SECRET_KEY }}" \
            POSTGRES_USER="${{ env.POSTGRES_USER }}" \
            POSTGRES_PASSWORD="${{ env.POSTGRES_PASSWORD }}" \
            PGADMIN_DEFAULT_EMAIL="${{ env.PGADMIN_DEFAULT_EMAIL }}" \
            PGADMIN_DEFAULT_PASSWORD="${{ env.PGADMIN_DEFAULT_PASSWORD }}" \
            PGADMIN_CONFIG_SERVER_MODE="${{ env.PGADMIN_CONFIG_SERVER_MODE }}" \
            ALLOWED_HOSTS="${{ env.SCANPERSON_ALLOWED_HOSTS }}" \
            ConnectionStrings__ScanPersonDb="${{ env.ConnectionStrings__ScanPersonDb }}" \
            POSTGRES_DB="${{ env.SCANPERSON_POSTGRES_DB }}" \
            HTMLWEBRU_API_KEY="${{ env.HTMLWEBRU_API_KEY }}" \
            AUTO_MAPPER_LICENSE_KEY="${{ env.AUTO_MAPPER_LICENSE_KEY }}" \
            PGDATA="${{ env.SCANPERSON_PGDATA }}" \
            APP_UID="${{ env.APP_UID }}" \
            HOST_HTTPS_PATH="${{ env.HOST_HTTPS_PATH }}" \
            docker compose up -d --build

            ls -l /home/${{ env.VM_USER }}/Repositories/Pet/Identity/Identity.Api/https/cert.pfx
            ls -l /home/${{ env.VM_USER }}/Repositories/Pet/ScanPerson/ScanPerson.WebApi/https/cert.pfx
            echo "$(ls -l /home/${{ env.VM_USER }}/Repositories/Pet/ScanPerson/ScanPerson.WebApi/https/cert.pfx)"
            echo "$(ls -l /home/${{ env.VM_USER }}/Repositories/Pet/Identity/Identity.Api/https/cert.pfx)"