# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CD github action

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI github action ]
    types: [completed]

jobs:
  continuous-delivery:
    name: Prepare host, push and up dockers
    runs-on: ubuntu-latest
    if: |
        ${{ (github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push' &&
        github.event_name == 'workflow_run' ||
        github.event_name == 'workflow_dispatch') }}
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      # Prepare before Deploy to VM and build containers
      - name: Prepare before deploy to VM and build containers
        uses: appleboy/ssh-action@3ca8a7c5359ac6ad91aa47f1946ece1c3b025004
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
          IS_REMOVE_IMAGE: ${{ vars.IS_REMOVE_IMAGE }}
          IS_REMOVE_VOLUMES: ${{ vars.IS_REMOVE_VOLUMES }}
          EXCLUDE_SERVICE_NAMES: browserbotapi|redis|mongodb|pgadmin|graylog|elasticsearch
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            FOR_REMOVE_CONTAINERS=$(docker ps -qa | grep -E -v "$(docker ps -qa --filter name="^(${{ env.EXCLUDE_SERVICE_NAMES }})")")
            echo "FOR_REMOVE_CONTAINERS: $FOR_REMOVE_CONTAINERS"
    
            echo "Check and stop running containers "
            if [ -n "$FOR_REMOVE_CONTAINERS" ]; then
              echo "Stopping running containers..."
              docker stop $FOR_REMOVE_CONTAINERS
            else
              echo "No running containers to stop."
            fi

            echo "Check and remove stopped containers"
            if [ -n "$FOR_REMOVE_CONTAINERS" ]; then
              echo "Removing stopped containers..."
              docker rm $FOR_REMOVE_CONTAINERS
            else
              echo "No stopped containers to remove."
            fi

            echo "Check and remove images (optional, but good for cleanup)."
            if [ ${{ env.IS_REMOVE_IMAGE }}='true' ]; then
              echo "Removing images..."
              docker image prune -f
            else
              echo "No images to remove."
            fi

            echo "Check and remove unused Docker volumes (optional, but good for cleanup)."
            if [ ${{ env.IS_REMOVE_VOLUMES }}='true' ]; then
              echo "Removing volumes..."
              docker volume prune -f
            else
              echo "No volumes to remove."
            fi

            echo "Ensure network exists or create it"
            if ! docker network ls | grep -q 'scanperson-network'; then
            echo "Create docker network - scanperson-network."
            docker network create -d bridge scanperson-network
            else
            echo "Network 'scanperson-network' is exists."
            fi

            echo "Change permission for Repositories folder."
            if [ ! -d "/home/${{ env.VM_USER }}/Repositories/Pet" ]; then
              echo "Creating Pet directory..."
              mkdir -p /home/${{ env.VM_USER }}/Repositories/Pet
            fi
            echo "Directory structure prepared."
            sudo chown -R ${{ env.VM_USER }}:${{ env.VM_USER }} /home/${{ env.VM_USER }}/Repositories

      # Copy files to VM
      - name: Copy files to VM
        uses: appleboy/scp-action@eb443bd4941c3334ee584c1915fcfa2001e8a86c
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "Repositories/Pet"
          rm: true

      # Deploy to VM and build containers
      - name: Deploy to VM and build containers
        uses: appleboy/ssh-action@3ca8a7c5359ac6ad91aa47f1946ece1c3b025004
        env:
          #Common
          VM_USER: ${{ secrets.VM_USER }}
          ASPNETCORE_ENVIRONMENT: ${{ vars.ASPNETCORE_ENVIRONMENT }}
          ASPNETCORE_Kestrel__Certificates__Default__Path: ${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PATH }}
          ASPNETCORE_Kestrel__Certificates__Default__Password: ${{ secrets.ASPNETCORE_KESTREL__CERTIFICATES__DEFAULT__PASSWORD }}
          JWT_OPTIONS_SECRET_KEY: ${{ secrets.JWT_OPTIONS_SECRET_KEY }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          HOST_HTTPS_PATH: ${{ vars.HOST_HTTPS_PATH }}
          IS_CACHE_ENABLE: ${{ vars.IS_CACHE_ENABLE }}
          CACHE_EXPIRATION: ${{ vars.CACHE_EXPIRATION }}

          # Shared solution
          GRAYLOG_PASSWORD_SECRET: ${{ secrets.GRAYLOG_PASSWORD_SECRET }}
          GRAYLOG_ROOT_PASSWORD_SHA2: ${{ secrets.GRAYLOG_ROOT_PASSWORD_SHA2 }}
          PGADMIN_DEFAULT_EMAIL: ${{ secrets.PGADMIN_DEFAULT_EMAIL }}
          PGADMIN_DEFAULT_PASSWORD: ${{ secrets.PGADMIN_DEFAULT_PASSWORD }}
          PGADMIN_CONFIG_SERVER_MODE: ${{ vars.PGADMIN_CONFIG_SERVER_MODE }}

          # ScanPerson solution
          SCANPERSON_ALLOWED_HOSTS: ${{ vars.SCANPERSON_ALLOWED_HOSTS }}
          ConnectionStrings__ScanPersonDb: ${{ secrets.CONNECTIONSTRINGS__SCANPERSONDB }}
          SCANPERSON_POSTGRES_DB: ${{ vars.SCANPERSON_POSTGRES_DB }}
          IDENTITY_API_DOMEN: ${{ vars.IDENTITY_API_DOMEN }}
          SCANPERSON_WEBAPI_DOMEN: ${{ vars.SCANPERSON_WEBAPI_DOMEN }}
          HTMLWEBRU_API_KEY: ${{ secrets.HTMLWEBRU_API_KEY }}
          AUTO_MAPPER_LICENSE_KEY: ${{ secrets.AUTO_MAPPER_LICENSE_KEY }}
          SCANPERSON_PGDATA: ${{ vars.SCANPERSON_PGDATA }}

          # Identity solution
          IDENTITY_ALLOWED_HOSTS: ${{ vars.IDENTITY_ALLOWED_HOSTS }}
          ConnectionStrings__IdentityDb: ${{ secrets.CONNECTIONSTRINGS__IDENTITYDB }}
          IDENTITY_POSTGRES_DB: ${{ vars.IDENTITY_POSTGRES_DB }}
          IDENTITY_PGDATA: ${{ vars.IDENTITY_PGDATA }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Add step for clone repository for first deploy in task #50
            # Navigate to the project directory on the VM
            cd Repositories/Pet

            # Obsolete remove block in task #22
            echo "Generating development certificates..."
            mkdir -p /home/${{ env.VM_USER }}/https
            dotnet dev-certs https --trust -ep /home/${{ env.VM_USER }}${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }} -p "${{ env.ASPNETCORE_Kestrel__Certificates__Default__Password }}"
            sudo chown -R ${{ env.VM_USER }}:${{ env.VM_USER }} /home/${{ env.VM_USER }}${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }}
            # this is an important setting for the dev certificate so that it can be accessed inside the container
            sudo chmod -R a+rwxrwxrwx /home/${{ env.VM_USER }}${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }} 
            sudo chown -R ${{ env.VM_USER }}:${{ env.VM_USER }} /home/${{ env.VM_USER }}/Repositories
            
            # Rebuild and restart the Docker Compose services for all solutions.
            # The --build flag forces Docker Compose to rebuild the images locally.

            # Graylog
            echo "Shared build and up."
            cd Shared

            GRAYLOG_PASSWORD_SECRET="${{ env.GRAYLOG_PASSWORD_SECRET }}" \
            GRAYLOG_ROOT_PASSWORD_SHA2="${{ env.GRAYLOG_ROOT_PASSWORD_SHA2 }}" \
            PGADMIN_DEFAULT_EMAIL="${{ env.PGADMIN_DEFAULT_EMAIL }}" \
            PGADMIN_DEFAULT_PASSWORD="${{ env.PGADMIN_DEFAULT_PASSWORD }}" \
            PGADMIN_CONFIG_SERVER_MODE="${{ env.PGADMIN_CONFIG_SERVER_MODE }}" \
            docker compose up -d --build
            
            echo "Identity build and up."
            cd ../Identity

            ASPNETCORE_ENVIRONMENT="${{ env.ASPNETCORE_ENVIRONMENT }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Path="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Password="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Password }}" \
            JWT_OPTIONS_SECRET_KEY="${{ env.JWT_OPTIONS_SECRET_KEY }}" \
            POSTGRES_USER="${{ env.POSTGRES_USER }}" \
            POSTGRES_PASSWORD="${{ env.POSTGRES_PASSWORD }}" \
            ALLOWED_HOSTS="${{ env.IDENTITY_ALLOWED_HOSTS }}" \
            ConnectionStrings__IdentityDb="${{ env.ConnectionStrings__IdentityDb }}" \
            IDENTITY_POSTGRES_DB="${{ env.IDENTITY_POSTGRES_DB }}" \
            PGDATA="${{ env.IDENTITY_PGDATA }}" \
            HOST_HTTPS_PATH="${{ env.HOST_HTTPS_PATH }}" \
            docker compose up -d --build

            echo "ScanPerson build and up."
            cd ../ScanPerson

            IDENTITY_API_DOMEN="${{ env.IDENTITY_API_DOMEN }}" \
            SCANPERSON_WEBAPI_DOMEN="${{ env.SCANPERSON_WEBAPI_DOMEN }}" \
            ASPNETCORE_ENVIRONMENT="${{ env.ASPNETCORE_ENVIRONMENT }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Path="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Path }}" \
            ASPNETCORE_Kestrel__Certificates__Default__Password="${{ env.ASPNETCORE_Kestrel__Certificates__Default__Password }}" \
            JWT_OPTIONS_SECRET_KEY="${{ env.JWT_OPTIONS_SECRET_KEY }}" \
            POSTGRES_USER="${{ env.POSTGRES_USER }}" \
            POSTGRES_PASSWORD="${{ env.POSTGRES_PASSWORD }}" \
            ALLOWED_HOSTS="${{ env.SCANPERSON_ALLOWED_HOSTS }}" \
            ConnectionStrings__ScanPersonDb="${{ env.ConnectionStrings__ScanPersonDb }}" \
            POSTGRES_DB="${{ env.SCANPERSON_POSTGRES_DB }}" \
            HTMLWEBRU_API_KEY="${{ env.HTMLWEBRU_API_KEY }}" \
            AUTO_MAPPER_LICENSE_KEY="${{ env.AUTO_MAPPER_LICENSE_KEY }}" \
            PGDATA="${{ env.SCANPERSON_PGDATA }}" \
            HOST_HTTPS_PATH="${{ env.HOST_HTTPS_PATH }}" \
            IS_CACHE_ENABLE="${{ env.IS_CACHE_ENABLE }}" \
            CACHE_EXPIRATION="${{ env.CACHE_EXPIRATION }}" \
            docker compose up -d --build
